sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tRxUhf3y1US395cJ4Cd
    access-key-secret: LmSHeALRPqPPLRjlqntLjue2ZwtQok
    bucket-name: takeout-sherrylxf